global:
  qsname: quickstart-puppet
  qsenv: dev
  reporting: true
  cis3bucket:  s3://quickstart-ci-bucket
  regions:
    - us-east-1
    - us-west-1
    - eu-west-1
    - us-west-2
    - ap-northeast-1
    - ap-northeast-2
    - ap-southeast-1
    - eu-central-1
    - ap-southeast-2
    - sa-east-1
    - ap-south-1

tests:
  qs_puppet:
    template_file: Puppet-QuickStart.template
    parameter_input: Puppet-QuickStart.json
